function dYdt = RotaryPendulum_ODE(t,Y,tau,I,m,l,Rl,g)
%ROTARYPENDULUM_ODE
%    DYDT = ROTARYPENDULUM_ODE(T,Y,TAU,I,M,L,RL,G)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Aug-2021 15:40:38

t2 = Rl.^2;
t3 = Y(2);
t4 = Y(3);
t5 = Y(4);
t6 = l.^2;
t7 = l.^3;
t8 = m.^2;
t11 = I.*1.2e+1;
t9 = cos(t4);
t10 = sin(t4);
t12 = t3.^2;
t13 = t5.^2;
t17 = m.*t2.*1.2e+1;
t14 = t9.^2;
t15 = t10.^2;
t16 = t10.^3;
t18 = m.*t6.*t15.*4.0;
t19 = m.*t2.*t14.*9.0;
t20 = -t19;
t21 = t11+t17+t18+t20;
t22 = 1.0./t21;
dYdt = [t3;(t22.*(l.*6.0e+1-l.*t3.*6.0e+1+l.*tau.*6.0e+4-Rl.*t5.*t9.*9.0-Rl.*m.*t6.*t10.*t13.*3.0e+4-m.*t3.*t5.*t7.*t9.*t10.*4.0e+4+Rl.*g.*l.*m.*t9.*t10.*4.5e+4+Rl.*m.*t6.*t10.*t12.*t14.*3.0e+4))./(l.*5.0e+3);t5;(t22.*(I.*t5.*-9.0-m.*t2.*t5.*9.0+g.*t7.*t8.*t16.*1.5e+4-m.*t5.*t6.*t15.*3.0+Rl.*l.*m.*t9.*4.5e+1+t6.^2.*t8.*t9.*t12.*t16.*1.0e+4+I.*g.*l.*m.*t10.*4.5e+4-Rl.*l.*m.*t3.*t9.*4.5e+1+Rl.*l.*m.*t9.*tau.*4.5e+4+g.*l.*t2.*t8.*t10.*4.5e+4+t2.*t6.*t8.*t9.*t10.*t12.*3.0e+4-t2.*t6.*t8.*t9.*t10.*t13.*2.25e+4+I.*m.*t6.*t9.*t10.*t12.*3.0e+4-Rl.*t3.*t5.*t7.*t8.*t10.*t14.*3.0e+4))./(m.*t6.*2.5e+3)];
